version: "3.8"

services:
  calculator-api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - JWT_SECRET=super-secret-jwt
